# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
DEVISE_SECRET_KEY: 2181a56194d5710d55fa4832b0c9e63d483961c58ad428dfc3875aa8c7f8f0d537443ca1d0f0e635b7258b14fe4c4238816ffc928b1f1cc203e9a1f2f0b592cf
SECRET_KEY_BASE: c7daee6f1b8c41fcd12c09d65b41181e353e62a93a1f6f80860c90653bb334a35c191901e49d7d47a39340ad13eb2ac9b25aeff3b8551999dccf778ab250f601
TWITTER_CONSUMER_KEY: csLhALwpwN6o8N0FAq6o8g
TWITTER_CONSUMER_SECRET: 6jiPkxX400ydKYQZf9x9abvj50o3vkY1wZ9Vz3d00
FACEBOOK_APP_ID: 215386701985679
FACEBOOK_SECRET_KEY: 9413ec1d503c3af67c45516616a86f34
GOOGLE_CLIENT_ID: 337350149652-tqe69km9ekpvbu4u52vdb45n9lsii6ae.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: jLjgILWyeD3nxelEJTinGYSq
AWS_BUCKET: stepupphotos
AWS_ACCESS_KEY_ID: AKIAIH6ZMYX3ZE3FMQ6A
AWS_SECRET_ACCESS_KEY: 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

DEV_MAILER_HOST: localhost:3000
PROD_MAILER_HOST: localhost:3000
TEST_MAILER_HOST:
