# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
#DEVISE_SECRET_KEY: 2181a56194d5710d55fa4832b0c9e63d483961c58ad428dfc3875aa8c7f8f0d537443ca1d0f0e635b7258b14fe4c4238816ffc928b1f1cc203e9a1f2f0b592cf
#SECRET_KEY_BASE: c7daee6f1b8c41fcd12c09d65b41181e353e62a93a1f6f80860c90653bb334a35c191901e49d7d47a39340ad13eb2ac9b25aeff3b8551999dccf778ab250f601
TWITTER_CONSUMER_KEY: csLhALwpwN6o8N0FAq6o8g
TWITTER_CONSUMER_SECRET: 6jiPkxX400ydKYQZf9x9abvj50o3vkY1wZ9Vz3d00
FACEBOOK_APP_ID: 1437940739750826
FACEBOOK_SECRET_KEY: 65c6a716c1f57f6e020ec2613377f5d7
GOOGLE_CLIENT_ID: 447748179737-u3ba6si3l94r926o6c0b3hglsv3jp2r8.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: eVXEkXBRz1KVJIAH_uXGLQt3
AWS_BUCKET: stepupphotos
AWS_ACCESS_KEY_ID: AKIAJRUXVBA4KGWII3FA
AWS_SECRET_ACCESS_KEY: 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

DEV_MAILER_HOST: localhost:3000
PROD_MAILER_HOST: localhost:3000
TEST_MAILER_HOST:
